# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/shaft/Slinky2D

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/shaft/Slinky2D

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/Cellar/cmake/3.24.2/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/Cellar/cmake/3.24.2/bin/cpack --config ./CPackSourceConfig.cmake /Users/shaft/Slinky2D/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.24.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"bin\" \"devel\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shaft/Slinky2D/CMakeFiles /Users/shaft/Slinky2D//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shaft/Slinky2D/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Slinky2D

# Build rule for target.
Slinky2D: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Slinky2D
.PHONY : Slinky2D

# fast build rule for target.
Slinky2D/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/build
.PHONY : Slinky2D/fast

#=============================================================================
# Target rules for targets named FallingBox

# Build rule for target.
FallingBox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FallingBox
.PHONY : FallingBox

# fast build rule for target.
FallingBox/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FallingBox.dir/build.make CMakeFiles/FallingBox.dir/build
.PHONY : FallingBox/fast

#=============================================================================
# Target rules for targets named Particles

# Build rule for target.
Particles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Particles
.PHONY : Particles

# fast build rule for target.
Particles/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Particles.dir/build.make CMakeFiles/Particles.dir/build
.PHONY : Particles/fast

#=============================================================================
# Target rules for targets named AABBTest

# Build rule for target.
AABBTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AABBTest
.PHONY : AABBTest

# fast build rule for target.
AABBTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AABBTest.dir/build.make CMakeFiles/AABBTest.dir/build
.PHONY : AABBTest/fast

#=============================================================================
# Target rules for targets named ParticleTreeTest

# Build rule for target.
ParticleTreeTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ParticleTreeTest
.PHONY : ParticleTreeTest

# fast build rule for target.
ParticleTreeTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleTreeTest.dir/build.make CMakeFiles/ParticleTreeTest.dir/build
.PHONY : ParticleTreeTest/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named sfml-system

# Build rule for target.
sfml-system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-system
.PHONY : sfml-system

# fast build rule for target.
sfml-system/fast:
	$(MAKE) $(MAKESILENT) -f 3rdparty/sfml/src/SFML/System/CMakeFiles/sfml-system.dir/build.make 3rdparty/sfml/src/SFML/System/CMakeFiles/sfml-system.dir/build
.PHONY : sfml-system/fast

#=============================================================================
# Target rules for targets named sfml-window

# Build rule for target.
sfml-window: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-window
.PHONY : sfml-window

# fast build rule for target.
sfml-window/fast:
	$(MAKE) $(MAKESILENT) -f 3rdparty/sfml/src/SFML/Window/CMakeFiles/sfml-window.dir/build.make 3rdparty/sfml/src/SFML/Window/CMakeFiles/sfml-window.dir/build
.PHONY : sfml-window/fast

#=============================================================================
# Target rules for targets named sfml-network

# Build rule for target.
sfml-network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-network
.PHONY : sfml-network

# fast build rule for target.
sfml-network/fast:
	$(MAKE) $(MAKESILENT) -f 3rdparty/sfml/src/SFML/Network/CMakeFiles/sfml-network.dir/build.make 3rdparty/sfml/src/SFML/Network/CMakeFiles/sfml-network.dir/build
.PHONY : sfml-network/fast

#=============================================================================
# Target rules for targets named sfml-graphics

# Build rule for target.
sfml-graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-graphics
.PHONY : sfml-graphics

# fast build rule for target.
sfml-graphics/fast:
	$(MAKE) $(MAKESILENT) -f 3rdparty/sfml/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build.make 3rdparty/sfml/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build
.PHONY : sfml-graphics/fast

#=============================================================================
# Target rules for targets named sfml-audio

# Build rule for target.
sfml-audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-audio
.PHONY : sfml-audio

# fast build rule for target.
sfml-audio/fast:
	$(MAKE) $(MAKESILENT) -f 3rdparty/sfml/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build.make 3rdparty/sfml/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build
.PHONY : sfml-audio/fast

examples/FallingBox/main.o: examples/FallingBox/main.cpp.o
.PHONY : examples/FallingBox/main.o

# target to build an object file
examples/FallingBox/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FallingBox.dir/build.make CMakeFiles/FallingBox.dir/examples/FallingBox/main.cpp.o
.PHONY : examples/FallingBox/main.cpp.o

examples/FallingBox/main.i: examples/FallingBox/main.cpp.i
.PHONY : examples/FallingBox/main.i

# target to preprocess a source file
examples/FallingBox/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FallingBox.dir/build.make CMakeFiles/FallingBox.dir/examples/FallingBox/main.cpp.i
.PHONY : examples/FallingBox/main.cpp.i

examples/FallingBox/main.s: examples/FallingBox/main.cpp.s
.PHONY : examples/FallingBox/main.s

# target to generate assembly for a file
examples/FallingBox/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FallingBox.dir/build.make CMakeFiles/FallingBox.dir/examples/FallingBox/main.cpp.s
.PHONY : examples/FallingBox/main.cpp.s

examples/Particles/main.o: examples/Particles/main.cpp.o
.PHONY : examples/Particles/main.o

# target to build an object file
examples/Particles/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Particles.dir/build.make CMakeFiles/Particles.dir/examples/Particles/main.cpp.o
.PHONY : examples/Particles/main.cpp.o

examples/Particles/main.i: examples/Particles/main.cpp.i
.PHONY : examples/Particles/main.i

# target to preprocess a source file
examples/Particles/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Particles.dir/build.make CMakeFiles/Particles.dir/examples/Particles/main.cpp.i
.PHONY : examples/Particles/main.cpp.i

examples/Particles/main.s: examples/Particles/main.cpp.s
.PHONY : examples/Particles/main.s

# target to generate assembly for a file
examples/Particles/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Particles.dir/build.make CMakeFiles/Particles.dir/examples/Particles/main.cpp.s
.PHONY : examples/Particles/main.cpp.s

src/Slinky/Collision/AABB.o: src/Slinky/Collision/AABB.cpp.o
.PHONY : src/Slinky/Collision/AABB.o

# target to build an object file
src/Slinky/Collision/AABB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Collision/AABB.cpp.o
.PHONY : src/Slinky/Collision/AABB.cpp.o

src/Slinky/Collision/AABB.i: src/Slinky/Collision/AABB.cpp.i
.PHONY : src/Slinky/Collision/AABB.i

# target to preprocess a source file
src/Slinky/Collision/AABB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Collision/AABB.cpp.i
.PHONY : src/Slinky/Collision/AABB.cpp.i

src/Slinky/Collision/AABB.s: src/Slinky/Collision/AABB.cpp.s
.PHONY : src/Slinky/Collision/AABB.s

# target to generate assembly for a file
src/Slinky/Collision/AABB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Collision/AABB.cpp.s
.PHONY : src/Slinky/Collision/AABB.cpp.s

src/Slinky/Collision/Body.o: src/Slinky/Collision/Body.cpp.o
.PHONY : src/Slinky/Collision/Body.o

# target to build an object file
src/Slinky/Collision/Body.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Collision/Body.cpp.o
.PHONY : src/Slinky/Collision/Body.cpp.o

src/Slinky/Collision/Body.i: src/Slinky/Collision/Body.cpp.i
.PHONY : src/Slinky/Collision/Body.i

# target to preprocess a source file
src/Slinky/Collision/Body.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Collision/Body.cpp.i
.PHONY : src/Slinky/Collision/Body.cpp.i

src/Slinky/Collision/Body.s: src/Slinky/Collision/Body.cpp.s
.PHONY : src/Slinky/Collision/Body.s

# target to generate assembly for a file
src/Slinky/Collision/Body.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Collision/Body.cpp.s
.PHONY : src/Slinky/Collision/Body.cpp.s

src/Slinky/Collision/BodyContact.o: src/Slinky/Collision/BodyContact.cpp.o
.PHONY : src/Slinky/Collision/BodyContact.o

# target to build an object file
src/Slinky/Collision/BodyContact.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Collision/BodyContact.cpp.o
.PHONY : src/Slinky/Collision/BodyContact.cpp.o

src/Slinky/Collision/BodyContact.i: src/Slinky/Collision/BodyContact.cpp.i
.PHONY : src/Slinky/Collision/BodyContact.i

# target to preprocess a source file
src/Slinky/Collision/BodyContact.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Collision/BodyContact.cpp.i
.PHONY : src/Slinky/Collision/BodyContact.cpp.i

src/Slinky/Collision/BodyContact.s: src/Slinky/Collision/BodyContact.cpp.s
.PHONY : src/Slinky/Collision/BodyContact.s

# target to generate assembly for a file
src/Slinky/Collision/BodyContact.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Collision/BodyContact.cpp.s
.PHONY : src/Slinky/Collision/BodyContact.cpp.s

src/Slinky/Containers/BodyQuadTree.o: src/Slinky/Containers/BodyQuadTree.cpp.o
.PHONY : src/Slinky/Containers/BodyQuadTree.o

# target to build an object file
src/Slinky/Containers/BodyQuadTree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Containers/BodyQuadTree.cpp.o
.PHONY : src/Slinky/Containers/BodyQuadTree.cpp.o

src/Slinky/Containers/BodyQuadTree.i: src/Slinky/Containers/BodyQuadTree.cpp.i
.PHONY : src/Slinky/Containers/BodyQuadTree.i

# target to preprocess a source file
src/Slinky/Containers/BodyQuadTree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Containers/BodyQuadTree.cpp.i
.PHONY : src/Slinky/Containers/BodyQuadTree.cpp.i

src/Slinky/Containers/BodyQuadTree.s: src/Slinky/Containers/BodyQuadTree.cpp.s
.PHONY : src/Slinky/Containers/BodyQuadTree.s

# target to generate assembly for a file
src/Slinky/Containers/BodyQuadTree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Containers/BodyQuadTree.cpp.s
.PHONY : src/Slinky/Containers/BodyQuadTree.cpp.s

src/Slinky/Containers/ParticleQuadTree.o: src/Slinky/Containers/ParticleQuadTree.cpp.o
.PHONY : src/Slinky/Containers/ParticleQuadTree.o

# target to build an object file
src/Slinky/Containers/ParticleQuadTree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Containers/ParticleQuadTree.cpp.o
.PHONY : src/Slinky/Containers/ParticleQuadTree.cpp.o

src/Slinky/Containers/ParticleQuadTree.i: src/Slinky/Containers/ParticleQuadTree.cpp.i
.PHONY : src/Slinky/Containers/ParticleQuadTree.i

# target to preprocess a source file
src/Slinky/Containers/ParticleQuadTree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Containers/ParticleQuadTree.cpp.i
.PHONY : src/Slinky/Containers/ParticleQuadTree.cpp.i

src/Slinky/Containers/ParticleQuadTree.s: src/Slinky/Containers/ParticleQuadTree.cpp.s
.PHONY : src/Slinky/Containers/ParticleQuadTree.s

# target to generate assembly for a file
src/Slinky/Containers/ParticleQuadTree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Containers/ParticleQuadTree.cpp.s
.PHONY : src/Slinky/Containers/ParticleQuadTree.cpp.s

src/Slinky/Core/World.o: src/Slinky/Core/World.cpp.o
.PHONY : src/Slinky/Core/World.o

# target to build an object file
src/Slinky/Core/World.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Core/World.cpp.o
.PHONY : src/Slinky/Core/World.cpp.o

src/Slinky/Core/World.i: src/Slinky/Core/World.cpp.i
.PHONY : src/Slinky/Core/World.i

# target to preprocess a source file
src/Slinky/Core/World.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Core/World.cpp.i
.PHONY : src/Slinky/Core/World.cpp.i

src/Slinky/Core/World.s: src/Slinky/Core/World.cpp.s
.PHONY : src/Slinky/Core/World.s

# target to generate assembly for a file
src/Slinky/Core/World.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Core/World.cpp.s
.PHONY : src/Slinky/Core/World.cpp.s

src/Slinky/Math/Vector2.o: src/Slinky/Math/Vector2.cpp.o
.PHONY : src/Slinky/Math/Vector2.o

# target to build an object file
src/Slinky/Math/Vector2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Math/Vector2.cpp.o
.PHONY : src/Slinky/Math/Vector2.cpp.o

src/Slinky/Math/Vector2.i: src/Slinky/Math/Vector2.cpp.i
.PHONY : src/Slinky/Math/Vector2.i

# target to preprocess a source file
src/Slinky/Math/Vector2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Math/Vector2.cpp.i
.PHONY : src/Slinky/Math/Vector2.cpp.i

src/Slinky/Math/Vector2.s: src/Slinky/Math/Vector2.cpp.s
.PHONY : src/Slinky/Math/Vector2.s

# target to generate assembly for a file
src/Slinky/Math/Vector2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Math/Vector2.cpp.s
.PHONY : src/Slinky/Math/Vector2.cpp.s

src/Slinky/Particle/Particle.o: src/Slinky/Particle/Particle.cpp.o
.PHONY : src/Slinky/Particle/Particle.o

# target to build an object file
src/Slinky/Particle/Particle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Particle/Particle.cpp.o
.PHONY : src/Slinky/Particle/Particle.cpp.o

src/Slinky/Particle/Particle.i: src/Slinky/Particle/Particle.cpp.i
.PHONY : src/Slinky/Particle/Particle.i

# target to preprocess a source file
src/Slinky/Particle/Particle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Particle/Particle.cpp.i
.PHONY : src/Slinky/Particle/Particle.cpp.i

src/Slinky/Particle/Particle.s: src/Slinky/Particle/Particle.cpp.s
.PHONY : src/Slinky/Particle/Particle.s

# target to generate assembly for a file
src/Slinky/Particle/Particle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Particle/Particle.cpp.s
.PHONY : src/Slinky/Particle/Particle.cpp.s

src/Slinky/Particle/ParticleContact.o: src/Slinky/Particle/ParticleContact.cpp.o
.PHONY : src/Slinky/Particle/ParticleContact.o

# target to build an object file
src/Slinky/Particle/ParticleContact.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Particle/ParticleContact.cpp.o
.PHONY : src/Slinky/Particle/ParticleContact.cpp.o

src/Slinky/Particle/ParticleContact.i: src/Slinky/Particle/ParticleContact.cpp.i
.PHONY : src/Slinky/Particle/ParticleContact.i

# target to preprocess a source file
src/Slinky/Particle/ParticleContact.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Particle/ParticleContact.cpp.i
.PHONY : src/Slinky/Particle/ParticleContact.cpp.i

src/Slinky/Particle/ParticleContact.s: src/Slinky/Particle/ParticleContact.cpp.s
.PHONY : src/Slinky/Particle/ParticleContact.s

# target to generate assembly for a file
src/Slinky/Particle/ParticleContact.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Particle/ParticleContact.cpp.s
.PHONY : src/Slinky/Particle/ParticleContact.cpp.s

src/Slinky/Particle/ParticleWorld.o: src/Slinky/Particle/ParticleWorld.cpp.o
.PHONY : src/Slinky/Particle/ParticleWorld.o

# target to build an object file
src/Slinky/Particle/ParticleWorld.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Particle/ParticleWorld.cpp.o
.PHONY : src/Slinky/Particle/ParticleWorld.cpp.o

src/Slinky/Particle/ParticleWorld.i: src/Slinky/Particle/ParticleWorld.cpp.i
.PHONY : src/Slinky/Particle/ParticleWorld.i

# target to preprocess a source file
src/Slinky/Particle/ParticleWorld.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Particle/ParticleWorld.cpp.i
.PHONY : src/Slinky/Particle/ParticleWorld.cpp.i

src/Slinky/Particle/ParticleWorld.s: src/Slinky/Particle/ParticleWorld.cpp.s
.PHONY : src/Slinky/Particle/ParticleWorld.s

# target to generate assembly for a file
src/Slinky/Particle/ParticleWorld.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Slinky2D.dir/build.make CMakeFiles/Slinky2D.dir/src/Slinky/Particle/ParticleWorld.cpp.s
.PHONY : src/Slinky/Particle/ParticleWorld.cpp.s

tests/AABBTest.o: tests/AABBTest.cpp.o
.PHONY : tests/AABBTest.o

# target to build an object file
tests/AABBTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AABBTest.dir/build.make CMakeFiles/AABBTest.dir/tests/AABBTest.cpp.o
.PHONY : tests/AABBTest.cpp.o

tests/AABBTest.i: tests/AABBTest.cpp.i
.PHONY : tests/AABBTest.i

# target to preprocess a source file
tests/AABBTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AABBTest.dir/build.make CMakeFiles/AABBTest.dir/tests/AABBTest.cpp.i
.PHONY : tests/AABBTest.cpp.i

tests/AABBTest.s: tests/AABBTest.cpp.s
.PHONY : tests/AABBTest.s

# target to generate assembly for a file
tests/AABBTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AABBTest.dir/build.make CMakeFiles/AABBTest.dir/tests/AABBTest.cpp.s
.PHONY : tests/AABBTest.cpp.s

tests/ParticleQuadTreeTest.o: tests/ParticleQuadTreeTest.cpp.o
.PHONY : tests/ParticleQuadTreeTest.o

# target to build an object file
tests/ParticleQuadTreeTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleTreeTest.dir/build.make CMakeFiles/ParticleTreeTest.dir/tests/ParticleQuadTreeTest.cpp.o
.PHONY : tests/ParticleQuadTreeTest.cpp.o

tests/ParticleQuadTreeTest.i: tests/ParticleQuadTreeTest.cpp.i
.PHONY : tests/ParticleQuadTreeTest.i

# target to preprocess a source file
tests/ParticleQuadTreeTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleTreeTest.dir/build.make CMakeFiles/ParticleTreeTest.dir/tests/ParticleQuadTreeTest.cpp.i
.PHONY : tests/ParticleQuadTreeTest.cpp.i

tests/ParticleQuadTreeTest.s: tests/ParticleQuadTreeTest.cpp.s
.PHONY : tests/ParticleQuadTreeTest.s

# target to generate assembly for a file
tests/ParticleQuadTreeTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParticleTreeTest.dir/build.make CMakeFiles/ParticleTreeTest.dir/tests/ParticleQuadTreeTest.cpp.s
.PHONY : tests/ParticleQuadTreeTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... AABBTest"
	@echo "... FallingBox"
	@echo "... ParticleTreeTest"
	@echo "... Particles"
	@echo "... Slinky2D"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... sfml-audio"
	@echo "... sfml-graphics"
	@echo "... sfml-network"
	@echo "... sfml-system"
	@echo "... sfml-window"
	@echo "... examples/FallingBox/main.o"
	@echo "... examples/FallingBox/main.i"
	@echo "... examples/FallingBox/main.s"
	@echo "... examples/Particles/main.o"
	@echo "... examples/Particles/main.i"
	@echo "... examples/Particles/main.s"
	@echo "... src/Slinky/Collision/AABB.o"
	@echo "... src/Slinky/Collision/AABB.i"
	@echo "... src/Slinky/Collision/AABB.s"
	@echo "... src/Slinky/Collision/Body.o"
	@echo "... src/Slinky/Collision/Body.i"
	@echo "... src/Slinky/Collision/Body.s"
	@echo "... src/Slinky/Collision/BodyContact.o"
	@echo "... src/Slinky/Collision/BodyContact.i"
	@echo "... src/Slinky/Collision/BodyContact.s"
	@echo "... src/Slinky/Containers/BodyQuadTree.o"
	@echo "... src/Slinky/Containers/BodyQuadTree.i"
	@echo "... src/Slinky/Containers/BodyQuadTree.s"
	@echo "... src/Slinky/Containers/ParticleQuadTree.o"
	@echo "... src/Slinky/Containers/ParticleQuadTree.i"
	@echo "... src/Slinky/Containers/ParticleQuadTree.s"
	@echo "... src/Slinky/Core/World.o"
	@echo "... src/Slinky/Core/World.i"
	@echo "... src/Slinky/Core/World.s"
	@echo "... src/Slinky/Math/Vector2.o"
	@echo "... src/Slinky/Math/Vector2.i"
	@echo "... src/Slinky/Math/Vector2.s"
	@echo "... src/Slinky/Particle/Particle.o"
	@echo "... src/Slinky/Particle/Particle.i"
	@echo "... src/Slinky/Particle/Particle.s"
	@echo "... src/Slinky/Particle/ParticleContact.o"
	@echo "... src/Slinky/Particle/ParticleContact.i"
	@echo "... src/Slinky/Particle/ParticleContact.s"
	@echo "... src/Slinky/Particle/ParticleWorld.o"
	@echo "... src/Slinky/Particle/ParticleWorld.i"
	@echo "... src/Slinky/Particle/ParticleWorld.s"
	@echo "... tests/AABBTest.o"
	@echo "... tests/AABBTest.i"
	@echo "... tests/AABBTest.s"
	@echo "... tests/ParticleQuadTreeTest.o"
	@echo "... tests/ParticleQuadTreeTest.i"
	@echo "... tests/ParticleQuadTreeTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

